### ISSUE TITLE
Go Live Checklist: Road Choice Canada

### ISSUE THREAD

**Issue by ZoeBeykirch** [aemsites/vg-roadchoice-com#28]
### Description:
Create dedicated multi-language websites for the Canadian market under Road Choice, supporting both French and English versions. These separate tickets should help streamline the development and testing processes for each market site while ensuring clarity in responsibilities and outcomes.

### Related tickets: 
https://github.com/hlxsites/vg-roadchoice-com/issues/222
https://github.com/hlxsites/vg-roadchoice-com/issues/258  - Mexico go-live is lower priority than Canada go-live.

### Acceptance Criteria:

- [x] Set up SharePoint folders specific to Canada. - [vg-roadchoice-ca](https://adobe.sharepoint.com/:f:/r/sites/HelixProjects/Shared%20Documents/sites/VolvoGroup/[vg-roadchoice-ca](https://adobe.sharepoint.com/:f:/r/sites/HelixProjects/Shared%20Documents/sites/VolvoGroup/vg-roadchoice-ca?csf=1&web=1&e=M6k40E)?csf=1&web=1&e=M6k40E)
- [x] Translations of the content as required per language.
- [ ] Setting configs for each location. This might be done by Darin but must be confirmed that everything is in place. @manuel-vara @dkuntze 

### Content Tasks 
 aemsites/vg-roadchoice-com#21
- [ ] Coordinate with DNS configurations for the domain (https://www.roadchoice.ca/fr-ca/). @Kannan-CM 
- [x] There is an English version of the site
- [x] There is a French Canadian version of the site
- [ ] Setting up the constant file configs per language
- [ ] Translate placeholder file per language
- [ ] Manage separate product data catalogs in Excel sheets tailored to Canada's offerings.
- [x] Utilize the USA website structure as a template for the Canadian site.
- [ ] aemsites/vg-roadchoice-com#23

### Testing Tasks
- [ ] QA team: Begin testing the new Road Choice Canada website preview (https://main--roadchoice-ca--volvogroup.aem.page/).

### Out of Scope
- [ ] Manage dealer locator for Canada market aemsites/vg-roadchoice-com-old#233 (not a blocker)
- [ ] Resolve any functional bugs to ensure full website functionality.
- [ ] @Kannan-CM to implement One Trust following Go-Live
- [ ] aemsites/vg-roadchoice-com#22 (for both Canada and Mexico in mono-repo)

### Go Live
- [ ] Approval from @janedbarra and team to go live

**Comment by ZoeBeykirch** [comment]
English version is priority 1, French is priority 2 (if we can't publish at the same time)

**Comment by bouchriy** [comment]
This issue has been migrated to Azure DevOps: https://dev.azure.com/volvo-digital-experience/DEX Platform/_workitems/edit/129774
