### ISSUE TITLE
Go Live Checklist: Road Choice Mexico 

### ISSUE THREAD

**Issue by ZoeBeykirch** [aemsites/vg-roadchoice-com#29]
### Description:
Establish a new Spanish-language website for the Mexican market under Road Choice, with potential for future English language support. These separate tickets should help streamline the development and testing processes for each market site while ensuring clarity in responsibilities and outcomes.

**Related tickets:** 
https://github.com/hlxsites/vg-roadchoice-com/issues/222

### Acceptance Criteria 

- [x] Create dedicated SharePoint folders for Mexico - [vg-roadchoice-mx](https://adobe.sharepoint.com/:f:/r/sites/HelixProjects/Shared%20Documents/sites/VolvoGroup/[vg-roadchoice-mx](https://adobe.sharepoint.com/:f:/r/sites/HelixProjects/Shared%20Documents/sites/VolvoGroup/vg-roadchoice-mx?csf=1&web=1&e=HZR1K6)?csf=1&web=1&e=HZR1K6)
- [x] Translations of the content sent to proof reading
- [ ] Translations approved/verified
- [ ] Setting up the constant file configs
- [x] Translate placeholder file
- [ ] Setting configs for each location. This might be done by Darin but must be confirmed that everything is in place.
- [ ] Manage separate product data catalogs in Excel sheets tailored to Mexico's offerings.
- [ ] Manage dealer locator for Mexico market (translations will be handled in a separate ticket)
- [ ] Mirror the structure of the USA website for the Mexican market site, other than the product categories which will only have the following: 
1. [Engine Cooling](https://www.roadchoice.com/part-category/engine-cooling) - Part listings for Radiators, Charge Air Coolers, Fan Clutches, Fan Clutch Kits, and Fan Clutch Valves
2.  [Suspension](https://www.roadchoice.com/part-category/suspension) - Part listings for Air Springs
3. [Engine](https://www.roadchoice.com/part-category/engine) - Part listings for V-Belts
4. [Electrical](https://www.roadchoice.com/part-category/electrical) - Part listings for Batteries

- [ ] Approval from @janedbarra and team to go live

### Out of Scope
aemsites/vg-roadchoice-com-old#233 for dealer locator translations will be handled after Go Live
