### ISSUE TITLE
Go Live Checklist: Road Choice Mexico 

### ISSUE THREAD

**Issue by alexiscoelho** [aemsites/vg-roadchoice-com#4]
### Description:

Establish a new Spanish-language website for the Mexican market under Road Choice, with potential for future English language support. These separate tickets should help streamline the development and testing processes for each market site while ensuring clarity in responsibilities and outcomes.

### Related Tickets: 
#28 

### Acceptance Criteria: 
- [x] Set up SharePoint folder specific to Mexico -  [vg-roadchoice-mx](https://adobe.sharepoint.com/:f:/r/sites/HelixProjects/Shared+Documents/sites/VolvoGroup/[vg-roadchoice-mx](https://adobe.sharepoint.com/:f:/r/sites/HelixProjects/Shared+Documents/sites/VolvoGroup/vg-roadchoice-mx?csf=1&web=1&e=HZR1K6)?csf=1&web=1&e=HZR1K6)
- [x] Translations of the content as required for Spanish.
- [x] Setting configs for each location. This might be done by Darin but must be confirmed that everything is in place. @manuel-vara @dkuntze

### Content Tasks 
- [ ] Config needed from @darin prior to DNS configurations by @Kannan-CM 
- [ ] Setting up the constant file configs for Spanish
- [ ] Translate placeholder file fro Spanish
- [ ] Manage separate product data catalogs in Excel sheets tailored to Mexico's offerings.
- [ ] Utilize the USA website structure as a template for the Mexico site.
- [ ]  Mirror the structure of the USA website for the Mexican market site, other than the product categories which will only have the following: 
1. [Engine Cooling](https://www.roadchoice.com/part-category/engine-cooling) - Part listings for Radiators, Charge Air Coolers, Fan Clutches, Fan Clutch Kits, and Fan Clutch Valves
2.  [Suspension](https://www.roadchoice.com/part-category/suspension) - Part listings for Air Springs
3. [Engine](https://www.roadchoice.com/part-category/engine) - Part listings for V-Belts
4. [Electrical](https://www.roadchoice.com/part-category/electrical) - Part listings for Batteries

### Testing Tasks 

- [ ] QA Team: Begin testing the new RoadChoice Mexico Website preview links

### Out of Scope

- [ ] Manage dealer locator #36 
- [ ] Resolve functional bugs to ensure full website functionality
- [ ] @Kannan-CM to implement OneTrust following GoLive
- [ ] #22 

### Go Live
- [ ] Approval from @janedbarra and team

**Comment by alexiscoelho** [comment]
**[<img src="https://avatars.githubusercontent.com/u/142249558?s=17&v=4" width="17" height="17"> @BeckyMedlin](https://github.com/BeckyMedlin)** [commented](https://github.com/hlxsites/vg-roadchoice-com/issues/258#issuecomment-2247907297) on 2024-07-24: 

> @janedbarra Please review this go-live checklist and advise if anything else needs to be added. Thank you!

**Comment by alexiscoelho** [comment]
**[<img src="https://avatars.githubusercontent.com/u/140720979?s=17&v=4" width="17" height="17"> @janedbarra](https://github.com/janedbarra)** [commented](https://github.com/hlxsites/vg-roadchoice-com/issues/258#issuecomment-2248013458) on 2024-07-24: 

> @BeckyMedlin - I can't think of anything else to add. Only comment I have is on this item " Mirror the structure of the USA website for the Mexican market site." The structure should be the same but I have listed out the product categories that are specific to Mexico (they won't have everything that our current site includes). 
> 
> 
> 
> For Mexico, I would only want to have the following category pages copied over for the .mx site:
> 
> •	[Engine Cooling](https://www.roadchoice.com/part-category/engine-cooling)
> 
> o	Part listings for Radiators, Charge Air Coolers, Fan Clutches, Fan Clutch Kits, and Fan Clutch Valves
> 
> 
> 
> •	[Suspension](https://www.roadchoice.com/part-category/suspension)
> 
> o	Part listings for Air Springs
> 
> 
> 
> •	[Engine](https://www.roadchoice.com/part-category/engine)
> 
> o	Part listings for V-Belts
> 
> 
> 
> •	[Electrical](https://www.roadchoice.com/part-category/electrical)
> 
> o	Part listings for Batteries

**Comment by alexiscoelho** [comment]
**[<img src="https://avatars.githubusercontent.com/u/125895595?s=17&v=4" width="17" height="17"> @ZoeBeykirch](https://github.com/ZoeBeykirch)** [commented](https://github.com/hlxsites/vg-roadchoice-com/issues/258#issuecomment-2248710910) on 2024-07-24: 

> @janedbarra Thank you! I have updated the ticket to include this :)

**Comment by mollyaljenkins** [comment]
Kamino cloned this issue to [hlxsites/vg-roadchoice-com](https://github.com/hlxsites/vg-roadchoice-com/issues/275)

**Comment by mollyaljenkins** [comment]
Kamino cloned this issue to [hlxsites/vg-roadchoice-com](https://github.com/hlxsites/vg-roadchoice-com/issues/278)

**Comment by mollyaljenkins** [comment]
Kamino cloned this issue to [hlxsites/vg-macktrucks-ca](https://github.com/hlxsites/vg-macktrucks-ca/issues/30)

**Comment by VladMano** [comment]
Testing completed has been completed.
The only subtask that remained untouched is:

- Dealer locator not in Spanish**(?)** - https://main--roadchoice-mx--volvogroup.aem.live/where-to-buy

There was no change as there is no Dealer Locator feed that is available in Spanish, as such, it is not an issue on content side.

**Comment by Kannan-CM** [comment]
We are working to set up the Roadchoice MX repo on Volvo Sharepoint and it is in middle of the process.
Might take somemore time to finish the set up.
